#!/usr/bin/env python3
"""Encode the corpus for the browser demo.

One character per beat keeps 1382 tunes small enough to inline in a page:
each beat is a chord code (root * 6 + quality, 0..71) mapped into a 72-character
alphabet chosen to need no escaping inside a JavaScript string literal.

Usage:  python scripts/build_web_data.py > web/corpus.js
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from namestd.corpus import load_corpus            # noqa: E402
from namestd.families import build_families       # noqa: E402

ALPHABET = (
    "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
    "abcdefghijklmnopqrstuvwxyz"
    "0123456789"
    "!#$%&()*+,"
)
assert len(ALPHABET) == 72 and len(set(ALPHABET)) == 72
assert not ({'"', "\\", "'", "`"} & set(ALPHABET))


def main() -> int:
    songs = load_corpus()
    families, family_of = build_families(songs)

    encoded = []
    for i, song in enumerate(songs):
        codes = song.codes()
        encoded.append({
            "t": song.title,
            "c": song.composer,
            "b": song.beats_per_bar,
            "f": family_of[i],
            "k": "".join(ALPHABET[int(code)] for code in codes),
        })

    family_names = [
        {"n": f.name, "s": len(f)} for f in families
    ]

    out = {
        "alphabet": ALPHABET,
        "songs": encoded,
        "families": family_names,
    }
    payload = json.dumps(out, separators=(",", ":"))
    print("// Generated by scripts/build_web_data.py - do not edit.")
    print(f"window.CORPUS = {payload};")

    total = sum(len(s["k"]) for s in encoded)
    print(f"// {len(encoded)} tunes, {total} beats, "
          f"{len(payload) // 1024} KB", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
